version: "3.8"

services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    restart: always
    ports:
      - ${VITE_APP_PORT_OUT}:${VITE_APP_PORT_IN}
    environment:
      - VITE_APP_ENV=${VITE_APP_ENV}
      - VITE_APP_PORT_IN=${VITE_APP_PORT_IN}
      - VITE_APP_PORT_OUT=${VITE_APP_PORT_OUT}
      - VITE_APP_BACK_URL=${VITE_APP_API_URL}
